rainforestapp/rf-stylez

ruby/rubocop.yml
This cop flags formations like the following:
```ruby
def foo(bar)
bar.each do |b|
do_something_with b
return if is_the_last_one? b
end
end
```
I've run into it a couple of times, and honestly I don't understand what
errors it's trying to prevent (it's easy to know the difference between
`break` and `return`).
@rainforestapp/devs 👍/👎❓
=> Disable Lint/NonLocalExitFromIterator cop

ruby/rubocop.yml
The cop doesn't like this (perfectly reasonable, IMO) construction in
RSpec tests:
```ruby
expect(foo).to match /bar/
```
@rainforestapp/devs 👍/👎❓
=> Disable Lint/AmbiguousRegexpLiteral cop

ruby/rubocop.yml
This enforces the Go-style trailing comma:
```ruby
[
a,
b,
c,
]
```
The advantage is that it's easier to add and remove items from the
literal.
@rainforestapp/devs 👍/👎❓
=> Enable Style/TrailingCommaInLiteral cop

lib/rf/stylez/version.rb, ruby/rubocop_lint.yml
I'm having the following error when running `bundle exec circlemator style-check`:
```
/home/ubuntu/nafta/vendor/bundle/ruby/2.3.0/gems/rf-stylez-0.2.4/ruby/rubocop_lint.yml: Lint/Eval has the wrong namespace - should be Security
```
This was caused by recent changes on Rubocop: https://github.com/bbatsov/rubocop/pull/3820
=> Move Lint/Eval to Security/Eval

lib/rf/stylez/version.rb, ruby/rubocop.yml
Enables the `Style/SignalException` cop that forces all exceptions to be raised via `raise` instead of `fail`.
=> RF-4000 Enable Style/SignalException cop

.circleci/config.yml
Rake release failed when trying to push a tag. We'll already have a tag, so no need for that, so I went back to `gem` command. Also fixes filters, as it is an `or` it triggered for master even without the tag. It *should* work this time.
=> RF-5192 use gem instead of rake

lib/rf/stylez/version.rb, ruby/rubocop.yml
to automate comments like...
... in the future :) 
defaults for this seem good to go:
- EnforcedStyle: slashes 
- AllowInnerSlashes: false (enforce `%r{}`)
=> RF-7959 Add Style/RegexpLiteral rule

lib/rf/stylez/version.rb, ruby/rubocop.yml
Our style guides prefers we don't use global variables or special
variables such as $_ / $. / etc.
=> Warn about global and special variables

README.md, lib/rf/stylez/version.rb, lib/rubocop/cop/lint/use_positive_int32_validator.rb
This causes breakage because byebug is only a development dependency and
the `require byebug'` is in non-develop code which doesn't have byebug
as a dependency.
=> Remove byebug include

.rubocop.yml, lib/rf/stylez/version.rb, lib/rubocop/cop/lint/no_bang_state_machine_events.rb, spec/rubocop/cop/lint/no_bang_state_machine_events_spec.rb, spec/spec_helper.rb
State machine parses symbols that are passed as event names and defines
some methods. For example, given event named `ship` it will define
`ship` that will fail gracefully by returning false and `ship!` that
will raise an error.
Unfortunately, should you decide to pass a symbol that already ends with
a `!` state_machine will only define the graceful method and end it with
a bang. That causes not only confusion, but also bugs and we have a
bunch of occurrences in our codebase hence this cop
=> Add NoBangStateMachineEvents Cop

lib/rf/stylez.rb, lib/rf/stylez/version.rb, lib/rubocop/cop/lint/no_untyped_raise.rb, spec/rubocop/cop/lint/no_untyped_raise.rb, spec/spec_helper.rb
This checks for code that throws untyped (or StandardError) exceptions which is generally a bad practice b/c it makes it hard to catch these exceptions without catching all sorts of other things and is generally not very descriptive.
=> Add check for raising untyped exceptions

lib/rf/stylez/version.rb, ruby/rubocop.yml
Remove the duplicate config for Naming/MethodName to stop the message:
> 102: `Naming/MethodName` is concealed by line 112
=> Remove duplicate config for Naming/MethodName

README.md, lib/rf/stylez/version.rb, rails/rubocop.yml, rf-stylez.gemspec
* I've added it in such a way that it can be enabled for Rails projects without it being forced upon unsuspecting Ruby-only projects (as described in the README changes).
* I haven't actually gone through all the cops yet to decide what should be on/off - I figure it'll be easier to see what the recommendations are and go from there.
* And I decided to bump the version up to 0.5.0 since this is adding a whole new set of cops - I thought that warranted more than a patch increase.
=> RF-17561 Add rubocop-rails so we can use the Rails-specific cops

.circleci/config.yml, lib/rf/stylez/version.rb, ruby/rubocop.yml
=> Actually make RSpec cops available when doing inherit_gem: rf-stylez

.circleci/config.yml, lib/rf/stylez/version.rb
Went with a minor rather than patch version update since the Rubocop changes are breaking (some cops were removed).
Changes since 0.7.2: https://github.com/rainforestapp/rf-stylez/compare/v0.7.2..v0.8.0.pre2
Once this is shipped, `circlemator` can be updated and the `style_check` CI job can use the `circlemator:latest` image once more.
=> v0.8.0 release (update rubocop dependencies)

.circleci/config.yml
Docker are changing their TOS to rate limit unauthenticated `docker pull`
from the start of November. The rate limiting is based on IP, so builds on
Circle will be immediately impacted. Use a paid-for account and contexts to
configure a user to pull down docker images for CI/CD.
=> RF-19896 Use DockerHub user for pulling down images

lib/rf/stylez/version.rb, rf-stylez.gemspec
Rf-stylez is our source of truth on Rubocop definitions os, with a more 
specific dependency definitions it can also become our source of truth on
what version of rubocop and it's extensions we run
=> RF-20100 Lock dependencies

rf-stylez.gemspec
In the past we've been adding RF Stylez to our Gemfiles and that's why
we needed the soft dependency.
It's no longer the case so let's pin a specific rubocop version
=> Pin specific rubocop version

lib/rf/stylez.rb, lib/rubocop/cop/lint/no_vcr_recording.rb, rf-stylez.gemspec, ruby/rubocop.yml, spec/rubocop/cop/lint/no_vcr_recording_spec.rb, spec/spec_helper.rb
This way we don't accidentally commit specs which could make network calls on every CI build due to a forgotten `record: :new_episodes`.
=> Add NoVCRRecording cop

lib/rf/stylez/version.rb
`style_check` will continue to fail until this release is pushed to RubyGems and the `circlemator` Docker image updated to use it.
=> Bump version to 0.12.0

lib/rf/stylez/version.rb, ruby/rubocop.yml
Writing better code comments is something that we brought up recently in misc discussions and the weekly backend meeting. I think enabling [the `Style/Documentation` cop](https://docs.rubocop.org/rubocop/cops_style.html#styledocumentation) could help us do this more as it'll flag at the `class`/`module` keyword unless there's at least one line of comment above. Please share your thoughts in the comments
=> Enable Style/Documentation to enforce top-level class comments

Gemfile, bin/rf-stylez, lib/rf/stylez.rb, lib/rf/stylez/version.rb, rf-stylez.gemspec, ruby/.reek.yml
Starter Reek config file ✨ Let's go through _all_ the warnings from [the defaults](https://github.com/troessner/reek/blob/master/docs/defaults.reek.yml) and check what we might want to override here. The YAML I'm committing now is not finalised!
Once it is finalised, we can configure a `pronto-reek` Github Action to comment on our PRs. I believe this would make more sense than blocking on `pre-push`, like we do with Rubocop, because Reek design-oriented warnings may require more effort to fix.
Reek does not support config inheritance, at least until https://github.com/troessner/reek/issues/1512, so I thought we can reuse our config with something like `reek -c $(rf-stylez reek-config-path)` in the pronto action.
Let's discuss!
=> Add .reek.yml

.circleci/config.yml, .github/workflows/pronto.yml, .gitignore, lib/rf/stylez/update_check.rb, lib/rf/stylez/version.rb, rf-stylez.gemspec
- I had to deprecate `SemanticVersioning` gem dependency which was causing issues and seems no longer maintained. Moreover it seems it was used for something that is included in `Gem` standard lib (https://medium.com/little-programming-joys/how-to-compare-version-strings-in-ruby-ced0916a4b71)
**THEN:**
After merge, we need to release the new gem version to rubygems (see README)
=> Upgrade to Ruby 3.2.0

bin/rf-stylez, lib/rf/stylez/version.rb
With `require 'bundler/setup'` running this command will use the Gemfile
in the current working directory. If the Gemfile doesn't include
rf-stylze then this means the path to the rf-stylez libraries is removed
from the $LOAD_PATH and the command will fail to require `rf/stylez`.
=> RF-26495 Remove bundler/setup from bin/rf-stylez

README.md
As part of an effort to deprecate Circlemator repository, we are removing all of its usages and references.
=> RF-26632 Remove circlemator reference in README

.circleci/config.yml, .github/workflows/pronto.yml, lib/rf/stylez/version.rb, rf-stylez.gemspec, ruby/rubocop.yml, spec/rubocop/cop/lint/no_bang_state_machine_events_spec.rb, spec/rubocop/cop/lint/no_http_party_spec.rb, spec/rubocop/cop/lint/no_json_spec.rb, spec/rubocop/cop/lint/no_vcr_recording_spec.rb, spec/rubocop/cop/lint/obscure_spec.rb, spec/rubocop/cop/lint/use_positive_int32_validator_spec.rb
* Updated the runtime dependency gems to their latest version
* Added linter to avoid `OpenStruct` usage
* Improved `pronto` checks performance
* Updated to version `1.0.1`
=> Update runtime gems and enable OpenStruct linter

lib/rf/stylez/version.rb, ruby/rubocop.yml
We were seeing lots of warnings due to using the new keyword syntax added in ruby 3.1 I think.
=> Set target ruby version 3.2

lib/rf/stylez/version.rb, rails/rubocop.yml, rf-stylez.gemspec
I enabled only some `rubocop-rails` cops that I thought should be OK by everyone.
Here is the full list of cops to see if we want to enable more https://docs.rubocop.org/rubocop-rails/cops.html
Another topic for discussion is that we have `DisabledByDefault: true` configured, so we have to opt-in to every cop rule we want. I wonder if we should try to reverse that configuration and opt out of what we don't want.
=> RF-32115 start using rubocop rails

Gemfile, lib/rf/stylez/update_check.rb, lib/rf/stylez/version.rb, lib/rubocop/cop/lint/no_grape_api.rb, lib/rubocop/cop/lint/no_http_party.rb, lib/rubocop/cop/lint/no_json.rb, lib/rubocop/cop/lint/no_untyped_raise.rb, lib/rubocop/cop/lint/obscure.rb, lib/rubocop/cop/lint/use_positive_int32_validator.rb, rails/rubocop.yml, rf-stylez.gemspec, ruby/rubocop.yml, spec/rubocop/cop/lint/no_bang_state_machine_events_spec.rb, spec/rubocop/cop/lint/no_grape_api_spec.rb, spec/rubocop/cop/lint/no_htt_party_spec.rb, spec/rubocop/cop/lint/no_json_spec.rb, spec/rubocop/cop/lint/no_untyped_raise_spec.rb, spec/rubocop/cop/lint/no_vcr_recording_spec.rb, spec/rubocop/cop/lint/obscure_spec.rb, spec/rubocop/cop/lint/use_positive_int32_validator_spec.rb
As the title suggests, it changes the configuration so that all cops are enabled by default, and we have to opt-out of the ones we don't want.
It will require some effort to detect which rules are the ones we didn't want to apply so that we explicitly turn them off.
=> Change cops default to true and we have to opt-out

.circleci/config.yml, .github/workflows/pronto.yml, lib/rf/stylez/version.rb, rails/rubocop.yml, rf-stylez.gemspec, ruby/rubocop.yml, spec/rf/stylez_spec.rb
* Copied the rules we were using on our main backend repository.
* Updated the dependency gems versions.
* Fixed some rubocop warnings.
* Releasing version 1.2.0
=> Update rubocop enabled and disabled rules 

rf-stylez.gemspec
Somehow after the previous PR https://github.com/rainforestapp/rf-stylez/pull/205 pushing to rubygems started failing, so reverting the changes to the `gemspec`.
=> Fix gemspec to make push to rubygems work

.circleci/config.yml, .github/workflows/pronto.yml, lib/rf/stylez/version.rb, rf-stylez.gemspec
Not sure if reverting these things will actually fix the push to rubygems.
If it's still broken after this, then probably the problem is not the code, but in the integration with rubygems or the task we are using might be deprecated.
=> Revert some changes to fix push to rubygems

.circleci/config.yml, .github/workflows/pronto.yml, Gemfile, lib/rf/stylez/version.rb, rf-stylez.gemspec, ruby/rubocop.yml
* Updated rubocop dependencies versions
* Added rubocop-performance
* Updated the supported Ruby version
=> Update rubocop and ruby versions, and add rubocop-performance

.circleci/config.yml, .github/workflows/pronto.yml, Gemfile, lib/rf/stylez/version.rb, rf-stylez.gemspec, ruby/rubocop.yml
https://app.circleci.com/pipelines/github/rainforestapp/rf-stylez/321/workflows/c34d7194-7d35-4bf9-a4e2-523ca7b4a219/jobs/644
```
ERROR:  While executing gem ... (NoMethodError)
undefined method `[]=' for nil
stack[depth][key] = val
^^^^^^^
/usr/local/lib/ruby/site_ruby/3.3.0/rubygems/yaml_serializer.rb:72:in `block in load'
/usr/local/lib/ruby/site_ruby/3.3.0/rubygems/yaml_serializer.rb:58:in `split'
/usr/local/lib/ruby/site_ruby/3.3.0/rubygems/yaml_serializer.rb:58:in `load'
/usr/local/lib/ruby/site_ruby/3.3.0/rubygems/config_file.rb:545:in `load_with_rubygems_config_hash'
/usr/local/lib/ruby/site_ruby/3.3.0/rubygems/config_file.rb:362:in `load_file'
/usr/local/lib/ruby/site_ruby/3.3.0/rubygems/config_file.rb:297:in `load_api_keys' …
```
=> Attempt to fix push to rubygems

.circleci/config.yml, .github/workflows/pronto.yml, Gemfile, lib/rf/stylez/version.rb, rf-stylez.gemspec, ruby/rubocop.yml
- Has been some time since we last updated them.
- Also set the repository Ruby version to the latest 3.3.6 and updated CircleCI and pronto scripts.
=> Update rubocop gems versions

lib/rf/stylez/version.rb, lib/rubocop/cop/lint/no_bang_state_machine_events.rb, lib/rubocop/cop/lint/no_grape_api.rb, lib/rubocop/cop/lint/no_http_party.rb, lib/rubocop/cop/lint/no_json.rb, lib/rubocop/cop/lint/no_untyped_raise.rb, lib/rubocop/cop/lint/obscure.rb, lib/rubocop/cop/lint/use_positive_int32_validator.rb
Example deprecation warning:
```
rf-stylez/lib/rubocop/cop/lint/no_grape_api.rb:15: warning: Inheriting from `RuboCop::Cop::Cop` is deprecated. Use `RuboCop::Cop::Base` instead.
For more information, see https://docs.rubocop.org/rubocop/v1_upgrade_notes.html.
```
This PR fixes those
=> Fix deprecation warning about inheriting from Cop instead of Base

.circleci/config.yml
Newer ruby is more strict when parsing the credentials yaml file, and the leading spaces we had in it are not good/valid yaml.
I tested this fix in the get_env repo here:
https://github.com/rainforestapp/get_env/pull/122
=> Fix pushing to rubygems with newer rubies

lib/rf/stylez/version.rb, rails/rubocop.yml
Warning said:
```
rubocop-rails extension supports plugin, specify `plugins: rubocop-rails` instead of `require: rubocop-rails` in /gems/rf-stylez-1.2.6/rails/rubocop.yml.
For more information, see https://docs.rubocop.org/rubocop/plugin_migration_guide.html.
```
=> Fix warning by replacing require with plugins
